# EpicRename Configuration File
# This is Color Code compatible (&)

# Don't change This
Config Version: 2

#Edit Messages below

no_permission: &cYou don't have permission!

not_enough_or_too_many_args: &cPlease put only one word. (Color Codes work with &)

