name: EpicRename
main: justbru00.rename.Rename
version: 1.8
description: Renames items.
author: Justin Brubaker


commands:
 rename:
       description: Renames your diamond pickaxe.       
 renameany:
       description: Renames any item. 
 lore:
       description: Relores any item.      