name: EpicRename
main: justbru00.rename.Rename
version: 1.2
description: Renames items.


commands:
 rename:
       description: Renames your diamond pickaxe.       
 renameany:
       description: Renames any item. 
 lore:
       description: Relores any item.      