name: EpicRename
main: justbru00.rename.Rename
version: 2.0
description: Renames items.
author: Justin Brubaker
softdepend: [Vault]

commands:
 rename:
       description: Renames your diamond pickaxe.       
 renameany:
       description: Renames any item. 
 lore:
       description: Relores any item.      