name: EpicRename
main: justbru00.rename.Rename
version: 1.0
description: Renames your diamond pickaxe.


commands:
 rename:
       description: Renames your diamond pickaxe.       
 renameany:
       description: Renames any item. 