name: EpicRename
main: com.gmail.justbru00.epic.rename.Main.Rename
version: 2.1
description: Renames items.
author: Justin Brubaker
softdepend: [Vault]

commands:
 rename:
       description: Renames your diamond pickaxe.       
 renameany:
       description: Renames any item. 
 lore:
       description: Relores any item.   
 renameentity:
       description: Gives you a nametag that is named.     
 epicrename:
       description: Help and version command.      