#EpicRename by Justin Brubaker. https://www.spigotmc.org/resources/epicrename.4341/
#Version 3.0


#Economy Features
economy:
  use: false
  costs:
    rename: 100
    lore: 100
    renameeentity: 100

# Should we auto update?    
auto_update: true