name: EpicRename
main: com.gmail.justbru00.epic.rename.main.v3.Main
version: 3.7.1-RC1
description: Performs different item modifications with easy to use commands.
authors: [Justin Brubaker,JustBru00,jayoevans]
softdepend: [Vault]
api-version: 1.13

commands:
  rename:
    description: Renames items.
    aliases: [eprename]
  lore:
    description: Relores any item.   
    aliases: [eplore]
  epicrename:
    description: Plugin information command.
    aliases: [epepicrename]
  setloreline:
    description: Sets a certain line of lore.
    aliases: [epsetloreline,sll]
  removeloreline:
    description: Remove a line of lore.     
    aliases: [epremoveloreline,rll]
  insertloreline:
    description: Insert a certain line of lore.
    aliases: [epinsertloreline,ill]
  glow:
    description: Adds an enchantment glow.  
    aliases: [epglow]
  removeglow:
    description: Removes an enchantment glow.     
    aliases: [epremoveglow]     
  import:
    description: Imports items from a URL.
    aliases: [epimport]
  export:
    description: Exports items to EpicRenameOnline.
    aliases: [epexport]    