name: EpicRename
main: com.gmail.justbru00.epic.rename.main.v3.Main
version: 3.1.0
description: Renames items.
author: Justin Brubaker
softdepend: [Vault]

commands:
 rename:
       description: Renames Items.
 lore:
       description: Relores any item.   
 epicrename:
       description: Help and version command.  
 setloreline:
       description: Sets a certain line of lore.
 removeloreline:
       description: Remove a line of lore.           