name: EpicRename
main: com.gmail.justbru00.epic.rename.main.v3.V3_Main
version: 3.0-DEV-ALPHA
description: Renames items.
author: Justin Brubaker
softdepend: [Vault]

commands:
 rename:
       description: Renames Items.
 lore:
       description: Relores any item.   
 renameentity:
       description: Gives you a nametag that is named.     
 epicrename:
       description: Help and version command.      