name: EpicRename
main: com.gmail.justbru00.epic.rename.main.v3.V3_Main
version: 3.0-ALPHA-DEV
description: Renames items.
author: Justin Brubaker
softdepend: [Vault]

commands:
 rename:
       description: Renames Items.
 lore:
       description: Relores any item.   
 renameentity:
       description: Gives you a nametag that is named.     
 epicrename:
       description: Help and version command.  
 setloreline:
       description: Sets a certain line of lore.
 removeloreline:
       description: Remove a line of lore.           